/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehicleSalesRouteImport } from './routes/_authenticated/vehicle-sales'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedMoneyCenterRouteImport } from './routes/_authenticated/money-center'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedECommerceRouteImport } from './routes/_authenticated/e-commerce'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDebtManagementRouteImport } from './routes/_authenticated/debt-management'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBankingRouteImport } from './routes/_authenticated/banking'
import { Route as AuthenticatedMoneyCenterIndexRouteImport } from './routes/_authenticated/money-center.index'
import { Route as AuthenticatedMoneyCenterTransfersRouteImport } from './routes/_authenticated/money-center.transfers'
import { Route as AuthenticatedMoneyCenterTransactionsRouteImport } from './routes/_authenticated/money-center.transactions'
import { Route as AuthenticatedMoneyCenterIncomeRouteImport } from './routes/_authenticated/money-center.income'
import { Route as AuthenticatedMoneyCenterExpensesRouteImport } from './routes/_authenticated/money-center.expenses'
import { Route as AuthenticatedMoneyCenterExpectedRouteImport } from './routes/_authenticated/money-center.expected'
import { Route as AuthenticatedMoneyCenterBudgetsRouteImport } from './routes/_authenticated/money-center.budgets'
import { Route as AuthenticatedMoneyCenterBillsRouteImport } from './routes/_authenticated/money-center.bills'
import { Route as AuthenticatedMoneyCenterAnalyticsRouteImport } from './routes/_authenticated/money-center.analytics'
import { Route as AuthenticatedMoneyCenterAccountsRouteImport } from './routes/_authenticated/money-center.accounts'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehicleSalesRoute =
  AuthenticatedVehicleSalesRouteImport.update({
    id: '/vehicle-sales',
    path: '/vehicle-sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyCenterRoute =
  AuthenticatedMoneyCenterRouteImport.update({
    id: '/money-center',
    path: '/money-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedECommerceRoute = AuthenticatedECommerceRouteImport.update({
  id: '/e-commerce',
  path: '/e-commerce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebtManagementRoute =
  AuthenticatedDebtManagementRouteImport.update({
    id: '/debt-management',
    path: '/debt-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankingRoute = AuthenticatedBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyCenterIndexRoute =
  AuthenticatedMoneyCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterTransfersRoute =
  AuthenticatedMoneyCenterTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterTransactionsRoute =
  AuthenticatedMoneyCenterTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterIncomeRoute =
  AuthenticatedMoneyCenterIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterExpensesRoute =
  AuthenticatedMoneyCenterExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterExpectedRoute =
  AuthenticatedMoneyCenterExpectedRouteImport.update({
    id: '/expected',
    path: '/expected',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterBudgetsRoute =
  AuthenticatedMoneyCenterBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterBillsRoute =
  AuthenticatedMoneyCenterBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterAnalyticsRoute =
  AuthenticatedMoneyCenterAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterAccountsRoute =
  AuthenticatedMoneyCenterAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt-management': typeof AuthenticatedDebtManagementRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/e-commerce': typeof AuthenticatedECommerceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/money-center': typeof AuthenticatedMoneyCenterRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/money-center/': typeof AuthenticatedMoneyCenterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt-management': typeof AuthenticatedDebtManagementRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/e-commerce': typeof AuthenticatedECommerceRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/people': typeof AuthenticatedPeopleRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/money-center': typeof AuthenticatedMoneyCenterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/banking': typeof AuthenticatedBankingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debt-management': typeof AuthenticatedDebtManagementRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/e-commerce': typeof AuthenticatedECommerceRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/money-center': typeof AuthenticatedMoneyCenterRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/_authenticated/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/_authenticated/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/_authenticated/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/_authenticated/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/_authenticated/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/_authenticated/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/_authenticated/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/_authenticated/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/_authenticated/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/_authenticated/money-center/': typeof AuthenticatedMoneyCenterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/banking'
    | '/calendar'
    | '/dashboard'
    | '/debt-management'
    | '/documents'
    | '/e-commerce'
    | '/goals'
    | '/marketing'
    | '/money-center'
    | '/notes'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/vehicle-sales'
    | '/money-center/accounts'
    | '/money-center/analytics'
    | '/money-center/bills'
    | '/money-center/budgets'
    | '/money-center/expected'
    | '/money-center/expenses'
    | '/money-center/income'
    | '/money-center/transactions'
    | '/money-center/transfers'
    | '/money-center/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/banking'
    | '/calendar'
    | '/dashboard'
    | '/debt-management'
    | '/documents'
    | '/e-commerce'
    | '/goals'
    | '/marketing'
    | '/notes'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/vehicle-sales'
    | '/money-center/accounts'
    | '/money-center/analytics'
    | '/money-center/bills'
    | '/money-center/budgets'
    | '/money-center/expected'
    | '/money-center/expenses'
    | '/money-center/income'
    | '/money-center/transactions'
    | '/money-center/transfers'
    | '/money-center'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/banking'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/debt-management'
    | '/_authenticated/documents'
    | '/_authenticated/e-commerce'
    | '/_authenticated/goals'
    | '/_authenticated/marketing'
    | '/_authenticated/money-center'
    | '/_authenticated/notes'
    | '/_authenticated/people'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/vehicle-sales'
    | '/_authenticated/money-center/accounts'
    | '/_authenticated/money-center/analytics'
    | '/_authenticated/money-center/bills'
    | '/_authenticated/money-center/budgets'
    | '/_authenticated/money-center/expected'
    | '/_authenticated/money-center/expenses'
    | '/_authenticated/money-center/income'
    | '/_authenticated/money-center/transactions'
    | '/_authenticated/money-center/transfers'
    | '/_authenticated/money-center/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehicle-sales': {
      id: '/_authenticated/vehicle-sales'
      path: '/vehicle-sales'
      fullPath: '/vehicle-sales'
      preLoaderRoute: typeof AuthenticatedVehicleSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-center': {
      id: '/_authenticated/money-center'
      path: '/money-center'
      fullPath: '/money-center'
      preLoaderRoute: typeof AuthenticatedMoneyCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e-commerce': {
      id: '/_authenticated/e-commerce'
      path: '/e-commerce'
      fullPath: '/e-commerce'
      preLoaderRoute: typeof AuthenticatedECommerceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debt-management': {
      id: '/_authenticated/debt-management'
      path: '/debt-management'
      fullPath: '/debt-management'
      preLoaderRoute: typeof AuthenticatedDebtManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banking': {
      id: '/_authenticated/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AuthenticatedBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-center/': {
      id: '/_authenticated/money-center/'
      path: '/'
      fullPath: '/money-center/'
      preLoaderRoute: typeof AuthenticatedMoneyCenterIndexRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/transfers': {
      id: '/_authenticated/money-center/transfers'
      path: '/transfers'
      fullPath: '/money-center/transfers'
      preLoaderRoute: typeof AuthenticatedMoneyCenterTransfersRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/transactions': {
      id: '/_authenticated/money-center/transactions'
      path: '/transactions'
      fullPath: '/money-center/transactions'
      preLoaderRoute: typeof AuthenticatedMoneyCenterTransactionsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/income': {
      id: '/_authenticated/money-center/income'
      path: '/income'
      fullPath: '/money-center/income'
      preLoaderRoute: typeof AuthenticatedMoneyCenterIncomeRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/expenses': {
      id: '/_authenticated/money-center/expenses'
      path: '/expenses'
      fullPath: '/money-center/expenses'
      preLoaderRoute: typeof AuthenticatedMoneyCenterExpensesRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/expected': {
      id: '/_authenticated/money-center/expected'
      path: '/expected'
      fullPath: '/money-center/expected'
      preLoaderRoute: typeof AuthenticatedMoneyCenterExpectedRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/budgets': {
      id: '/_authenticated/money-center/budgets'
      path: '/budgets'
      fullPath: '/money-center/budgets'
      preLoaderRoute: typeof AuthenticatedMoneyCenterBudgetsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/bills': {
      id: '/_authenticated/money-center/bills'
      path: '/bills'
      fullPath: '/money-center/bills'
      preLoaderRoute: typeof AuthenticatedMoneyCenterBillsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/analytics': {
      id: '/_authenticated/money-center/analytics'
      path: '/analytics'
      fullPath: '/money-center/analytics'
      preLoaderRoute: typeof AuthenticatedMoneyCenterAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/accounts': {
      id: '/_authenticated/money-center/accounts'
      path: '/accounts'
      fullPath: '/money-center/accounts'
      preLoaderRoute: typeof AuthenticatedMoneyCenterAccountsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
  }
}

interface AuthenticatedMoneyCenterRouteChildren {
  AuthenticatedMoneyCenterAccountsRoute: typeof AuthenticatedMoneyCenterAccountsRoute
  AuthenticatedMoneyCenterAnalyticsRoute: typeof AuthenticatedMoneyCenterAnalyticsRoute
  AuthenticatedMoneyCenterBillsRoute: typeof AuthenticatedMoneyCenterBillsRoute
  AuthenticatedMoneyCenterBudgetsRoute: typeof AuthenticatedMoneyCenterBudgetsRoute
  AuthenticatedMoneyCenterExpectedRoute: typeof AuthenticatedMoneyCenterExpectedRoute
  AuthenticatedMoneyCenterExpensesRoute: typeof AuthenticatedMoneyCenterExpensesRoute
  AuthenticatedMoneyCenterIncomeRoute: typeof AuthenticatedMoneyCenterIncomeRoute
  AuthenticatedMoneyCenterTransactionsRoute: typeof AuthenticatedMoneyCenterTransactionsRoute
  AuthenticatedMoneyCenterTransfersRoute: typeof AuthenticatedMoneyCenterTransfersRoute
  AuthenticatedMoneyCenterIndexRoute: typeof AuthenticatedMoneyCenterIndexRoute
}

const AuthenticatedMoneyCenterRouteChildren: AuthenticatedMoneyCenterRouteChildren =
  {
    AuthenticatedMoneyCenterAccountsRoute:
      AuthenticatedMoneyCenterAccountsRoute,
    AuthenticatedMoneyCenterAnalyticsRoute:
      AuthenticatedMoneyCenterAnalyticsRoute,
    AuthenticatedMoneyCenterBillsRoute: AuthenticatedMoneyCenterBillsRoute,
    AuthenticatedMoneyCenterBudgetsRoute: AuthenticatedMoneyCenterBudgetsRoute,
    AuthenticatedMoneyCenterExpectedRoute:
      AuthenticatedMoneyCenterExpectedRoute,
    AuthenticatedMoneyCenterExpensesRoute:
      AuthenticatedMoneyCenterExpensesRoute,
    AuthenticatedMoneyCenterIncomeRoute: AuthenticatedMoneyCenterIncomeRoute,
    AuthenticatedMoneyCenterTransactionsRoute:
      AuthenticatedMoneyCenterTransactionsRoute,
    AuthenticatedMoneyCenterTransfersRoute:
      AuthenticatedMoneyCenterTransfersRoute,
    AuthenticatedMoneyCenterIndexRoute: AuthenticatedMoneyCenterIndexRoute,
  }

const AuthenticatedMoneyCenterRouteWithChildren =
  AuthenticatedMoneyCenterRoute._addFileChildren(
    AuthenticatedMoneyCenterRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBankingRoute: typeof AuthenticatedBankingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtManagementRoute: typeof AuthenticatedDebtManagementRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedECommerceRoute: typeof AuthenticatedECommerceRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMoneyCenterRoute: typeof AuthenticatedMoneyCenterRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVehicleSalesRoute: typeof AuthenticatedVehicleSalesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBankingRoute: AuthenticatedBankingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtManagementRoute: AuthenticatedDebtManagementRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedECommerceRoute: AuthenticatedECommerceRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMoneyCenterRoute: AuthenticatedMoneyCenterRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVehicleSalesRoute: AuthenticatedVehicleSalesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
