/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAurenRouteImport } from './routes/_authenticated/auren'
import { Route as AuthenticatedBankingRouteImport } from './routes/_authenticated/banking'
import { Route as AuthenticatedBusinessesRouteImport } from './routes/_authenticated/businesses'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDebtManagementRouteImport } from './routes/_authenticated/debt-management'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedECommerceRouteImport } from './routes/_authenticated/e-commerce'
import { Route as AuthenticatedGoalsRouteImport } from './routes/_authenticated/goals'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedMissionsRouteImport } from './routes/_authenticated/missions'
import { Route as AuthenticatedMoneyCenterRouteImport } from './routes/_authenticated/money-center'
import { Route as AuthenticatedNotesRouteImport } from './routes/_authenticated/notes'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedPeopleRouteImport } from './routes/_authenticated/people'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as AuthenticatedVehicleSalesRouteImport } from './routes/_authenticated/vehicle-sales'
import { Route as AuthenticatedECommerceIndexRouteImport } from './routes/_authenticated/e-commerce.index'
import { Route as AuthenticatedECommerceAdsRouteImport } from './routes/_authenticated/e-commerce.ads'
import { Route as AuthenticatedECommerceCompetitorsRouteImport } from './routes/_authenticated/e-commerce.competitors'
import { Route as AuthenticatedECommerceCustomersRouteImport } from './routes/_authenticated/e-commerce.customers'
import { Route as AuthenticatedECommerceInventoryRouteImport } from './routes/_authenticated/e-commerce.inventory'
import { Route as AuthenticatedECommerceLandingPagesRouteImport } from './routes/_authenticated/e-commerce.landing-pages'
import { Route as AuthenticatedECommerceMarketRouteImport } from './routes/_authenticated/e-commerce.market'
import { Route as AuthenticatedECommerceMarketingRouteImport } from './routes/_authenticated/e-commerce.marketing'
import { Route as AuthenticatedECommerceOrdersRouteImport } from './routes/_authenticated/e-commerce.orders'
import { Route as AuthenticatedECommerceProductsRouteImport } from './routes/_authenticated/e-commerce.products'
import { Route as AuthenticatedECommerceReportsRouteImport } from './routes/_authenticated/e-commerce.reports'
import { Route as AuthenticatedECommerceSettingsRouteImport } from './routes/_authenticated/e-commerce.settings'
import { Route as AuthenticatedMoneyCenterIndexRouteImport } from './routes/_authenticated/money-center.index'
import { Route as AuthenticatedMoneyCenterAccountsRouteImport } from './routes/_authenticated/money-center.accounts'
import { Route as AuthenticatedMoneyCenterAnalyticsRouteImport } from './routes/_authenticated/money-center.analytics'
import { Route as AuthenticatedMoneyCenterBillsRouteImport } from './routes/_authenticated/money-center.bills'
import { Route as AuthenticatedMoneyCenterBudgetsRouteImport } from './routes/_authenticated/money-center.budgets'
import { Route as AuthenticatedMoneyCenterExpectedRouteImport } from './routes/_authenticated/money-center.expected'
import { Route as AuthenticatedMoneyCenterExpensesRouteImport } from './routes/_authenticated/money-center.expenses'
import { Route as AuthenticatedMoneyCenterIncomeRouteImport } from './routes/_authenticated/money-center.income'
import { Route as AuthenticatedMoneyCenterTransactionsRouteImport } from './routes/_authenticated/money-center.transactions'
import { Route as AuthenticatedMoneyCenterTransfersRouteImport } from './routes/_authenticated/money-center.transfers'
import { Route as AuthenticatedPeopleIndexRouteImport } from './routes/_authenticated/people.index'
import { Route as AuthenticatedPeopleLeadsRouteImport } from './routes/_authenticated/people.leads'
import { Route as AuthenticatedPeopleContactsIdRouteImport } from './routes/_authenticated/people.contacts.$id'
import { Route as AuthenticatedPeopleLeadsIdRouteImport } from './routes/_authenticated/people.leads.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAurenRoute = AuthenticatedAurenRouteImport.update({
  id: '/auren',
  path: '/auren',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBankingRoute = AuthenticatedBankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBusinessesRoute = AuthenticatedBusinessesRouteImport.update({
  id: '/businesses',
  path: '/businesses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebtManagementRoute =
  AuthenticatedDebtManagementRouteImport.update({
    id: '/debt-management',
    path: '/debt-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedECommerceRoute = AuthenticatedECommerceRouteImport.update({
  id: '/e-commerce',
  path: '/e-commerce',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMissionsRoute = AuthenticatedMissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMoneyCenterRoute =
  AuthenticatedMoneyCenterRouteImport.update({
    id: '/money-center',
    path: '/money-center',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedNotesRoute = AuthenticatedNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleRoute = AuthenticatedPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVehicleSalesRoute =
  AuthenticatedVehicleSalesRouteImport.update({
    id: '/vehicle-sales',
    path: '/vehicle-sales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedECommerceIndexRoute =
  AuthenticatedECommerceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceAdsRoute =
  AuthenticatedECommerceAdsRouteImport.update({
    id: '/ads',
    path: '/ads',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceCompetitorsRoute =
  AuthenticatedECommerceCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceCustomersRoute =
  AuthenticatedECommerceCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceInventoryRoute =
  AuthenticatedECommerceInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceLandingPagesRoute =
  AuthenticatedECommerceLandingPagesRouteImport.update({
    id: '/landing-pages',
    path: '/landing-pages',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceMarketRoute =
  AuthenticatedECommerceMarketRouteImport.update({
    id: '/market',
    path: '/market',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceMarketingRoute =
  AuthenticatedECommerceMarketingRouteImport.update({
    id: '/marketing',
    path: '/marketing',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceOrdersRoute =
  AuthenticatedECommerceOrdersRouteImport.update({
    id: '/orders',
    path: '/orders',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceProductsRoute =
  AuthenticatedECommerceProductsRouteImport.update({
    id: '/products',
    path: '/products',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceReportsRoute =
  AuthenticatedECommerceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedECommerceSettingsRoute =
  AuthenticatedECommerceSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedECommerceRoute,
  } as any)
const AuthenticatedMoneyCenterIndexRoute =
  AuthenticatedMoneyCenterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterAccountsRoute =
  AuthenticatedMoneyCenterAccountsRouteImport.update({
    id: '/accounts',
    path: '/accounts',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterAnalyticsRoute =
  AuthenticatedMoneyCenterAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterBillsRoute =
  AuthenticatedMoneyCenterBillsRouteImport.update({
    id: '/bills',
    path: '/bills',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterBudgetsRoute =
  AuthenticatedMoneyCenterBudgetsRouteImport.update({
    id: '/budgets',
    path: '/budgets',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterExpectedRoute =
  AuthenticatedMoneyCenterExpectedRouteImport.update({
    id: '/expected',
    path: '/expected',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterExpensesRoute =
  AuthenticatedMoneyCenterExpensesRouteImport.update({
    id: '/expenses',
    path: '/expenses',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterIncomeRoute =
  AuthenticatedMoneyCenterIncomeRouteImport.update({
    id: '/income',
    path: '/income',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterTransactionsRoute =
  AuthenticatedMoneyCenterTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedMoneyCenterTransfersRoute =
  AuthenticatedMoneyCenterTransfersRouteImport.update({
    id: '/transfers',
    path: '/transfers',
    getParentRoute: () => AuthenticatedMoneyCenterRoute,
  } as any)
const AuthenticatedPeopleIndexRoute =
  AuthenticatedPeopleIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedPeopleLeadsRoute =
  AuthenticatedPeopleLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedPeopleContactsIdRoute =
  AuthenticatedPeopleContactsIdRouteImport.update({
    id: '/contacts/$id',
    path: '/contacts/$id',
    getParentRoute: () => AuthenticatedPeopleRoute,
  } as any)
const AuthenticatedPeopleLeadsIdRoute =
  AuthenticatedPeopleLeadsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedPeopleLeadsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auren': typeof AuthenticatedAurenRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/businesses': typeof AuthenticatedBusinessesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt-management': typeof AuthenticatedDebtManagementRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/e-commerce': typeof AuthenticatedECommerceRouteWithChildren
  '/goals': typeof AuthenticatedGoalsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/money-center': typeof AuthenticatedMoneyCenterRouteWithChildren
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/people': typeof AuthenticatedPeopleRouteWithChildren
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/e-commerce/ads': typeof AuthenticatedECommerceAdsRoute
  '/e-commerce/competitors': typeof AuthenticatedECommerceCompetitorsRoute
  '/e-commerce/customers': typeof AuthenticatedECommerceCustomersRoute
  '/e-commerce/inventory': typeof AuthenticatedECommerceInventoryRoute
  '/e-commerce/landing-pages': typeof AuthenticatedECommerceLandingPagesRoute
  '/e-commerce/market': typeof AuthenticatedECommerceMarketRoute
  '/e-commerce/marketing': typeof AuthenticatedECommerceMarketingRoute
  '/e-commerce/orders': typeof AuthenticatedECommerceOrdersRoute
  '/e-commerce/products': typeof AuthenticatedECommerceProductsRoute
  '/e-commerce/reports': typeof AuthenticatedECommerceReportsRoute
  '/e-commerce/settings': typeof AuthenticatedECommerceSettingsRoute
  '/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/people/leads': typeof AuthenticatedPeopleLeadsRouteWithChildren
  '/e-commerce/': typeof AuthenticatedECommerceIndexRoute
  '/money-center/': typeof AuthenticatedMoneyCenterIndexRoute
  '/people/': typeof AuthenticatedPeopleIndexRoute
  '/people/contacts/$id': typeof AuthenticatedPeopleContactsIdRoute
  '/people/leads/$id': typeof AuthenticatedPeopleLeadsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auren': typeof AuthenticatedAurenRoute
  '/banking': typeof AuthenticatedBankingRoute
  '/businesses': typeof AuthenticatedBusinessesRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/debt-management': typeof AuthenticatedDebtManagementRoute
  '/documents': typeof AuthenticatedDocumentsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/missions': typeof AuthenticatedMissionsRoute
  '/notes': typeof AuthenticatedNotesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tasks': typeof AuthenticatedTasksRoute
  '/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/e-commerce/ads': typeof AuthenticatedECommerceAdsRoute
  '/e-commerce/competitors': typeof AuthenticatedECommerceCompetitorsRoute
  '/e-commerce/customers': typeof AuthenticatedECommerceCustomersRoute
  '/e-commerce/inventory': typeof AuthenticatedECommerceInventoryRoute
  '/e-commerce/landing-pages': typeof AuthenticatedECommerceLandingPagesRoute
  '/e-commerce/market': typeof AuthenticatedECommerceMarketRoute
  '/e-commerce/marketing': typeof AuthenticatedECommerceMarketingRoute
  '/e-commerce/orders': typeof AuthenticatedECommerceOrdersRoute
  '/e-commerce/products': typeof AuthenticatedECommerceProductsRoute
  '/e-commerce/reports': typeof AuthenticatedECommerceReportsRoute
  '/e-commerce/settings': typeof AuthenticatedECommerceSettingsRoute
  '/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/people/leads': typeof AuthenticatedPeopleLeadsRouteWithChildren
  '/e-commerce': typeof AuthenticatedECommerceIndexRoute
  '/money-center': typeof AuthenticatedMoneyCenterIndexRoute
  '/people': typeof AuthenticatedPeopleIndexRoute
  '/people/contacts/$id': typeof AuthenticatedPeopleContactsIdRoute
  '/people/leads/$id': typeof AuthenticatedPeopleLeadsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/auren': typeof AuthenticatedAurenRoute
  '/_authenticated/banking': typeof AuthenticatedBankingRoute
  '/_authenticated/businesses': typeof AuthenticatedBusinessesRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/debt-management': typeof AuthenticatedDebtManagementRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRoute
  '/_authenticated/e-commerce': typeof AuthenticatedECommerceRouteWithChildren
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/missions': typeof AuthenticatedMissionsRoute
  '/_authenticated/money-center': typeof AuthenticatedMoneyCenterRouteWithChildren
  '/_authenticated/notes': typeof AuthenticatedNotesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/people': typeof AuthenticatedPeopleRouteWithChildren
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRoute
  '/_authenticated/vehicle-sales': typeof AuthenticatedVehicleSalesRoute
  '/_authenticated/e-commerce/ads': typeof AuthenticatedECommerceAdsRoute
  '/_authenticated/e-commerce/competitors': typeof AuthenticatedECommerceCompetitorsRoute
  '/_authenticated/e-commerce/customers': typeof AuthenticatedECommerceCustomersRoute
  '/_authenticated/e-commerce/inventory': typeof AuthenticatedECommerceInventoryRoute
  '/_authenticated/e-commerce/landing-pages': typeof AuthenticatedECommerceLandingPagesRoute
  '/_authenticated/e-commerce/market': typeof AuthenticatedECommerceMarketRoute
  '/_authenticated/e-commerce/marketing': typeof AuthenticatedECommerceMarketingRoute
  '/_authenticated/e-commerce/orders': typeof AuthenticatedECommerceOrdersRoute
  '/_authenticated/e-commerce/products': typeof AuthenticatedECommerceProductsRoute
  '/_authenticated/e-commerce/reports': typeof AuthenticatedECommerceReportsRoute
  '/_authenticated/e-commerce/settings': typeof AuthenticatedECommerceSettingsRoute
  '/_authenticated/money-center/accounts': typeof AuthenticatedMoneyCenterAccountsRoute
  '/_authenticated/money-center/analytics': typeof AuthenticatedMoneyCenterAnalyticsRoute
  '/_authenticated/money-center/bills': typeof AuthenticatedMoneyCenterBillsRoute
  '/_authenticated/money-center/budgets': typeof AuthenticatedMoneyCenterBudgetsRoute
  '/_authenticated/money-center/expected': typeof AuthenticatedMoneyCenterExpectedRoute
  '/_authenticated/money-center/expenses': typeof AuthenticatedMoneyCenterExpensesRoute
  '/_authenticated/money-center/income': typeof AuthenticatedMoneyCenterIncomeRoute
  '/_authenticated/money-center/transactions': typeof AuthenticatedMoneyCenterTransactionsRoute
  '/_authenticated/money-center/transfers': typeof AuthenticatedMoneyCenterTransfersRoute
  '/_authenticated/people/leads': typeof AuthenticatedPeopleLeadsRouteWithChildren
  '/_authenticated/e-commerce/': typeof AuthenticatedECommerceIndexRoute
  '/_authenticated/money-center/': typeof AuthenticatedMoneyCenterIndexRoute
  '/_authenticated/people/': typeof AuthenticatedPeopleIndexRoute
  '/_authenticated/people/contacts/$id': typeof AuthenticatedPeopleContactsIdRoute
  '/_authenticated/people/leads/$id': typeof AuthenticatedPeopleLeadsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auren'
    | '/banking'
    | '/businesses'
    | '/calendar'
    | '/dashboard'
    | '/debt-management'
    | '/documents'
    | '/e-commerce'
    | '/goals'
    | '/library'
    | '/marketing'
    | '/missions'
    | '/money-center'
    | '/notes'
    | '/notifications'
    | '/people'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/vehicle-sales'
    | '/e-commerce/ads'
    | '/e-commerce/competitors'
    | '/e-commerce/customers'
    | '/e-commerce/inventory'
    | '/e-commerce/landing-pages'
    | '/e-commerce/market'
    | '/e-commerce/marketing'
    | '/e-commerce/orders'
    | '/e-commerce/products'
    | '/e-commerce/reports'
    | '/e-commerce/settings'
    | '/money-center/accounts'
    | '/money-center/analytics'
    | '/money-center/bills'
    | '/money-center/budgets'
    | '/money-center/expected'
    | '/money-center/expenses'
    | '/money-center/income'
    | '/money-center/transactions'
    | '/money-center/transfers'
    | '/people/leads'
    | '/e-commerce/'
    | '/money-center/'
    | '/people/'
    | '/people/contacts/$id'
    | '/people/leads/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auren'
    | '/banking'
    | '/businesses'
    | '/calendar'
    | '/dashboard'
    | '/debt-management'
    | '/documents'
    | '/goals'
    | '/library'
    | '/marketing'
    | '/missions'
    | '/notes'
    | '/notifications'
    | '/reports'
    | '/settings'
    | '/tasks'
    | '/vehicle-sales'
    | '/e-commerce/ads'
    | '/e-commerce/competitors'
    | '/e-commerce/customers'
    | '/e-commerce/inventory'
    | '/e-commerce/landing-pages'
    | '/e-commerce/market'
    | '/e-commerce/marketing'
    | '/e-commerce/orders'
    | '/e-commerce/products'
    | '/e-commerce/reports'
    | '/e-commerce/settings'
    | '/money-center/accounts'
    | '/money-center/analytics'
    | '/money-center/bills'
    | '/money-center/budgets'
    | '/money-center/expected'
    | '/money-center/expenses'
    | '/money-center/income'
    | '/money-center/transactions'
    | '/money-center/transfers'
    | '/people/leads'
    | '/e-commerce'
    | '/money-center'
    | '/people'
    | '/people/contacts/$id'
    | '/people/leads/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/auren'
    | '/_authenticated/banking'
    | '/_authenticated/businesses'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/debt-management'
    | '/_authenticated/documents'
    | '/_authenticated/e-commerce'
    | '/_authenticated/goals'
    | '/_authenticated/library'
    | '/_authenticated/marketing'
    | '/_authenticated/missions'
    | '/_authenticated/money-center'
    | '/_authenticated/notes'
    | '/_authenticated/notifications'
    | '/_authenticated/people'
    | '/_authenticated/reports'
    | '/_authenticated/settings'
    | '/_authenticated/tasks'
    | '/_authenticated/vehicle-sales'
    | '/_authenticated/e-commerce/ads'
    | '/_authenticated/e-commerce/competitors'
    | '/_authenticated/e-commerce/customers'
    | '/_authenticated/e-commerce/inventory'
    | '/_authenticated/e-commerce/landing-pages'
    | '/_authenticated/e-commerce/market'
    | '/_authenticated/e-commerce/marketing'
    | '/_authenticated/e-commerce/orders'
    | '/_authenticated/e-commerce/products'
    | '/_authenticated/e-commerce/reports'
    | '/_authenticated/e-commerce/settings'
    | '/_authenticated/money-center/accounts'
    | '/_authenticated/money-center/analytics'
    | '/_authenticated/money-center/bills'
    | '/_authenticated/money-center/budgets'
    | '/_authenticated/money-center/expected'
    | '/_authenticated/money-center/expenses'
    | '/_authenticated/money-center/income'
    | '/_authenticated/money-center/transactions'
    | '/_authenticated/money-center/transfers'
    | '/_authenticated/people/leads'
    | '/_authenticated/e-commerce/'
    | '/_authenticated/money-center/'
    | '/_authenticated/people/'
    | '/_authenticated/people/contacts/$id'
    | '/_authenticated/people/leads/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/auren': {
      id: '/_authenticated/auren'
      path: '/auren'
      fullPath: '/auren'
      preLoaderRoute: typeof AuthenticatedAurenRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/banking': {
      id: '/_authenticated/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof AuthenticatedBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/businesses': {
      id: '/_authenticated/businesses'
      path: '/businesses'
      fullPath: '/businesses'
      preLoaderRoute: typeof AuthenticatedBusinessesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debt-management': {
      id: '/_authenticated/debt-management'
      path: '/debt-management'
      fullPath: '/debt-management'
      preLoaderRoute: typeof AuthenticatedDebtManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e-commerce': {
      id: '/_authenticated/e-commerce'
      path: '/e-commerce'
      fullPath: '/e-commerce'
      preLoaderRoute: typeof AuthenticatedECommerceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/missions': {
      id: '/_authenticated/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof AuthenticatedMissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/money-center': {
      id: '/_authenticated/money-center'
      path: '/money-center'
      fullPath: '/money-center'
      preLoaderRoute: typeof AuthenticatedMoneyCenterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notes': {
      id: '/_authenticated/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof AuthenticatedNotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people': {
      id: '/_authenticated/people'
      path: '/people'
      fullPath: '/people'
      preLoaderRoute: typeof AuthenticatedPeopleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vehicle-sales': {
      id: '/_authenticated/vehicle-sales'
      path: '/vehicle-sales'
      fullPath: '/vehicle-sales'
      preLoaderRoute: typeof AuthenticatedVehicleSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/e-commerce/': {
      id: '/_authenticated/e-commerce/'
      path: '/'
      fullPath: '/e-commerce/'
      preLoaderRoute: typeof AuthenticatedECommerceIndexRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/ads': {
      id: '/_authenticated/e-commerce/ads'
      path: '/ads'
      fullPath: '/e-commerce/ads'
      preLoaderRoute: typeof AuthenticatedECommerceAdsRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/competitors': {
      id: '/_authenticated/e-commerce/competitors'
      path: '/competitors'
      fullPath: '/e-commerce/competitors'
      preLoaderRoute: typeof AuthenticatedECommerceCompetitorsRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/customers': {
      id: '/_authenticated/e-commerce/customers'
      path: '/customers'
      fullPath: '/e-commerce/customers'
      preLoaderRoute: typeof AuthenticatedECommerceCustomersRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/inventory': {
      id: '/_authenticated/e-commerce/inventory'
      path: '/inventory'
      fullPath: '/e-commerce/inventory'
      preLoaderRoute: typeof AuthenticatedECommerceInventoryRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/landing-pages': {
      id: '/_authenticated/e-commerce/landing-pages'
      path: '/landing-pages'
      fullPath: '/e-commerce/landing-pages'
      preLoaderRoute: typeof AuthenticatedECommerceLandingPagesRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/market': {
      id: '/_authenticated/e-commerce/market'
      path: '/market'
      fullPath: '/e-commerce/market'
      preLoaderRoute: typeof AuthenticatedECommerceMarketRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/marketing': {
      id: '/_authenticated/e-commerce/marketing'
      path: '/marketing'
      fullPath: '/e-commerce/marketing'
      preLoaderRoute: typeof AuthenticatedECommerceMarketingRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/orders': {
      id: '/_authenticated/e-commerce/orders'
      path: '/orders'
      fullPath: '/e-commerce/orders'
      preLoaderRoute: typeof AuthenticatedECommerceOrdersRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/products': {
      id: '/_authenticated/e-commerce/products'
      path: '/products'
      fullPath: '/e-commerce/products'
      preLoaderRoute: typeof AuthenticatedECommerceProductsRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/reports': {
      id: '/_authenticated/e-commerce/reports'
      path: '/reports'
      fullPath: '/e-commerce/reports'
      preLoaderRoute: typeof AuthenticatedECommerceReportsRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/e-commerce/settings': {
      id: '/_authenticated/e-commerce/settings'
      path: '/settings'
      fullPath: '/e-commerce/settings'
      preLoaderRoute: typeof AuthenticatedECommerceSettingsRouteImport
      parentRoute: typeof AuthenticatedECommerceRoute
    }
    '/_authenticated/money-center/': {
      id: '/_authenticated/money-center/'
      path: '/'
      fullPath: '/money-center/'
      preLoaderRoute: typeof AuthenticatedMoneyCenterIndexRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/accounts': {
      id: '/_authenticated/money-center/accounts'
      path: '/accounts'
      fullPath: '/money-center/accounts'
      preLoaderRoute: typeof AuthenticatedMoneyCenterAccountsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/analytics': {
      id: '/_authenticated/money-center/analytics'
      path: '/analytics'
      fullPath: '/money-center/analytics'
      preLoaderRoute: typeof AuthenticatedMoneyCenterAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/bills': {
      id: '/_authenticated/money-center/bills'
      path: '/bills'
      fullPath: '/money-center/bills'
      preLoaderRoute: typeof AuthenticatedMoneyCenterBillsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/budgets': {
      id: '/_authenticated/money-center/budgets'
      path: '/budgets'
      fullPath: '/money-center/budgets'
      preLoaderRoute: typeof AuthenticatedMoneyCenterBudgetsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/expected': {
      id: '/_authenticated/money-center/expected'
      path: '/expected'
      fullPath: '/money-center/expected'
      preLoaderRoute: typeof AuthenticatedMoneyCenterExpectedRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/expenses': {
      id: '/_authenticated/money-center/expenses'
      path: '/expenses'
      fullPath: '/money-center/expenses'
      preLoaderRoute: typeof AuthenticatedMoneyCenterExpensesRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/income': {
      id: '/_authenticated/money-center/income'
      path: '/income'
      fullPath: '/money-center/income'
      preLoaderRoute: typeof AuthenticatedMoneyCenterIncomeRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/transactions': {
      id: '/_authenticated/money-center/transactions'
      path: '/transactions'
      fullPath: '/money-center/transactions'
      preLoaderRoute: typeof AuthenticatedMoneyCenterTransactionsRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/money-center/transfers': {
      id: '/_authenticated/money-center/transfers'
      path: '/transfers'
      fullPath: '/money-center/transfers'
      preLoaderRoute: typeof AuthenticatedMoneyCenterTransfersRouteImport
      parentRoute: typeof AuthenticatedMoneyCenterRoute
    }
    '/_authenticated/people/': {
      id: '/_authenticated/people/'
      path: '/'
      fullPath: '/people/'
      preLoaderRoute: typeof AuthenticatedPeopleIndexRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/people/leads': {
      id: '/_authenticated/people/leads'
      path: '/leads'
      fullPath: '/people/leads'
      preLoaderRoute: typeof AuthenticatedPeopleLeadsRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/people/contacts/$id': {
      id: '/_authenticated/people/contacts/$id'
      path: '/contacts/$id'
      fullPath: '/people/contacts/$id'
      preLoaderRoute: typeof AuthenticatedPeopleContactsIdRouteImport
      parentRoute: typeof AuthenticatedPeopleRoute
    }
    '/_authenticated/people/leads/$id': {
      id: '/_authenticated/people/leads/$id'
      path: '/$id'
      fullPath: '/people/leads/$id'
      preLoaderRoute: typeof AuthenticatedPeopleLeadsIdRouteImport
      parentRoute: typeof AuthenticatedPeopleLeadsRoute
    }
  }
}

interface AuthenticatedECommerceRouteChildren {
  AuthenticatedECommerceAdsRoute: typeof AuthenticatedECommerceAdsRoute
  AuthenticatedECommerceCompetitorsRoute: typeof AuthenticatedECommerceCompetitorsRoute
  AuthenticatedECommerceCustomersRoute: typeof AuthenticatedECommerceCustomersRoute
  AuthenticatedECommerceInventoryRoute: typeof AuthenticatedECommerceInventoryRoute
  AuthenticatedECommerceLandingPagesRoute: typeof AuthenticatedECommerceLandingPagesRoute
  AuthenticatedECommerceMarketRoute: typeof AuthenticatedECommerceMarketRoute
  AuthenticatedECommerceMarketingRoute: typeof AuthenticatedECommerceMarketingRoute
  AuthenticatedECommerceOrdersRoute: typeof AuthenticatedECommerceOrdersRoute
  AuthenticatedECommerceProductsRoute: typeof AuthenticatedECommerceProductsRoute
  AuthenticatedECommerceReportsRoute: typeof AuthenticatedECommerceReportsRoute
  AuthenticatedECommerceSettingsRoute: typeof AuthenticatedECommerceSettingsRoute
  AuthenticatedECommerceIndexRoute: typeof AuthenticatedECommerceIndexRoute
}

const AuthenticatedECommerceRouteChildren: AuthenticatedECommerceRouteChildren =
  {
    AuthenticatedECommerceAdsRoute: AuthenticatedECommerceAdsRoute,
    AuthenticatedECommerceCompetitorsRoute:
      AuthenticatedECommerceCompetitorsRoute,
    AuthenticatedECommerceCustomersRoute: AuthenticatedECommerceCustomersRoute,
    AuthenticatedECommerceInventoryRoute: AuthenticatedECommerceInventoryRoute,
    AuthenticatedECommerceLandingPagesRoute:
      AuthenticatedECommerceLandingPagesRoute,
    AuthenticatedECommerceMarketRoute: AuthenticatedECommerceMarketRoute,
    AuthenticatedECommerceMarketingRoute: AuthenticatedECommerceMarketingRoute,
    AuthenticatedECommerceOrdersRoute: AuthenticatedECommerceOrdersRoute,
    AuthenticatedECommerceProductsRoute: AuthenticatedECommerceProductsRoute,
    AuthenticatedECommerceReportsRoute: AuthenticatedECommerceReportsRoute,
    AuthenticatedECommerceSettingsRoute: AuthenticatedECommerceSettingsRoute,
    AuthenticatedECommerceIndexRoute: AuthenticatedECommerceIndexRoute,
  }

const AuthenticatedECommerceRouteWithChildren =
  AuthenticatedECommerceRoute._addFileChildren(
    AuthenticatedECommerceRouteChildren,
  )

interface AuthenticatedMoneyCenterRouteChildren {
  AuthenticatedMoneyCenterAccountsRoute: typeof AuthenticatedMoneyCenterAccountsRoute
  AuthenticatedMoneyCenterAnalyticsRoute: typeof AuthenticatedMoneyCenterAnalyticsRoute
  AuthenticatedMoneyCenterBillsRoute: typeof AuthenticatedMoneyCenterBillsRoute
  AuthenticatedMoneyCenterBudgetsRoute: typeof AuthenticatedMoneyCenterBudgetsRoute
  AuthenticatedMoneyCenterExpectedRoute: typeof AuthenticatedMoneyCenterExpectedRoute
  AuthenticatedMoneyCenterExpensesRoute: typeof AuthenticatedMoneyCenterExpensesRoute
  AuthenticatedMoneyCenterIncomeRoute: typeof AuthenticatedMoneyCenterIncomeRoute
  AuthenticatedMoneyCenterTransactionsRoute: typeof AuthenticatedMoneyCenterTransactionsRoute
  AuthenticatedMoneyCenterTransfersRoute: typeof AuthenticatedMoneyCenterTransfersRoute
  AuthenticatedMoneyCenterIndexRoute: typeof AuthenticatedMoneyCenterIndexRoute
}

const AuthenticatedMoneyCenterRouteChildren: AuthenticatedMoneyCenterRouteChildren =
  {
    AuthenticatedMoneyCenterAccountsRoute:
      AuthenticatedMoneyCenterAccountsRoute,
    AuthenticatedMoneyCenterAnalyticsRoute:
      AuthenticatedMoneyCenterAnalyticsRoute,
    AuthenticatedMoneyCenterBillsRoute: AuthenticatedMoneyCenterBillsRoute,
    AuthenticatedMoneyCenterBudgetsRoute: AuthenticatedMoneyCenterBudgetsRoute,
    AuthenticatedMoneyCenterExpectedRoute:
      AuthenticatedMoneyCenterExpectedRoute,
    AuthenticatedMoneyCenterExpensesRoute:
      AuthenticatedMoneyCenterExpensesRoute,
    AuthenticatedMoneyCenterIncomeRoute: AuthenticatedMoneyCenterIncomeRoute,
    AuthenticatedMoneyCenterTransactionsRoute:
      AuthenticatedMoneyCenterTransactionsRoute,
    AuthenticatedMoneyCenterTransfersRoute:
      AuthenticatedMoneyCenterTransfersRoute,
    AuthenticatedMoneyCenterIndexRoute: AuthenticatedMoneyCenterIndexRoute,
  }

const AuthenticatedMoneyCenterRouteWithChildren =
  AuthenticatedMoneyCenterRoute._addFileChildren(
    AuthenticatedMoneyCenterRouteChildren,
  )

interface AuthenticatedPeopleLeadsRouteChildren {
  AuthenticatedPeopleLeadsIdRoute: typeof AuthenticatedPeopleLeadsIdRoute
}

const AuthenticatedPeopleLeadsRouteChildren: AuthenticatedPeopleLeadsRouteChildren =
  {
    AuthenticatedPeopleLeadsIdRoute: AuthenticatedPeopleLeadsIdRoute,
  }

const AuthenticatedPeopleLeadsRouteWithChildren =
  AuthenticatedPeopleLeadsRoute._addFileChildren(
    AuthenticatedPeopleLeadsRouteChildren,
  )

interface AuthenticatedPeopleRouteChildren {
  AuthenticatedPeopleLeadsRoute: typeof AuthenticatedPeopleLeadsRouteWithChildren
  AuthenticatedPeopleIndexRoute: typeof AuthenticatedPeopleIndexRoute
  AuthenticatedPeopleContactsIdRoute: typeof AuthenticatedPeopleContactsIdRoute
}

const AuthenticatedPeopleRouteChildren: AuthenticatedPeopleRouteChildren = {
  AuthenticatedPeopleLeadsRoute: AuthenticatedPeopleLeadsRouteWithChildren,
  AuthenticatedPeopleIndexRoute: AuthenticatedPeopleIndexRoute,
  AuthenticatedPeopleContactsIdRoute: AuthenticatedPeopleContactsIdRoute,
}

const AuthenticatedPeopleRouteWithChildren =
  AuthenticatedPeopleRoute._addFileChildren(AuthenticatedPeopleRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAurenRoute: typeof AuthenticatedAurenRoute
  AuthenticatedBankingRoute: typeof AuthenticatedBankingRoute
  AuthenticatedBusinessesRoute: typeof AuthenticatedBusinessesRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDebtManagementRoute: typeof AuthenticatedDebtManagementRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRoute
  AuthenticatedECommerceRoute: typeof AuthenticatedECommerceRouteWithChildren
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMissionsRoute: typeof AuthenticatedMissionsRoute
  AuthenticatedMoneyCenterRoute: typeof AuthenticatedMoneyCenterRouteWithChildren
  AuthenticatedNotesRoute: typeof AuthenticatedNotesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedPeopleRoute: typeof AuthenticatedPeopleRouteWithChildren
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRoute
  AuthenticatedVehicleSalesRoute: typeof AuthenticatedVehicleSalesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAurenRoute: AuthenticatedAurenRoute,
  AuthenticatedBankingRoute: AuthenticatedBankingRoute,
  AuthenticatedBusinessesRoute: AuthenticatedBusinessesRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDebtManagementRoute: AuthenticatedDebtManagementRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRoute,
  AuthenticatedECommerceRoute: AuthenticatedECommerceRouteWithChildren,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMissionsRoute: AuthenticatedMissionsRoute,
  AuthenticatedMoneyCenterRoute: AuthenticatedMoneyCenterRouteWithChildren,
  AuthenticatedNotesRoute: AuthenticatedNotesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedPeopleRoute: AuthenticatedPeopleRouteWithChildren,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRoute,
  AuthenticatedVehicleSalesRoute: AuthenticatedVehicleSalesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
